// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CommentHandler is an autogenerated mock type for the CommentHandler type
type CommentHandler struct {
	mock.Mock
}

// Comment provides a mock function with given fields: _a0, _a1
func (_m *CommentHandler) Comment(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Comments provides a mock function with given fields: _a0, _a1
func (_m *CommentHandler) Comments(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
