// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "instagram-go/domain"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// LikeRepository is an autogenerated mock type for the LikeRepository type
type LikeRepository struct {
	mock.Mock
}

// DeleteLike provides a mock function with given fields: _a0
func (_m *LikeRepository) DeleteLike(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindLikes provides a mock function with given fields: _a0
func (_m *LikeRepository) FindLikes(_a0 interface{}) (*[]primitive.M, error) {
	ret := _m.Called(_a0)

	var r0 *[]primitive.M
	if rf, ok := ret.Get(0).(func(interface{}) *[]primitive.M); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]primitive.M)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneLike provides a mock function with given fields: _a0
func (_m *LikeRepository) FindOneLike(_a0 string) (*domain.Like, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Like
	if rf, ok := ret.Get(0).(func(string) *domain.Like); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Like)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLike provides a mock function with given fields: _a0
func (_m *LikeRepository) InsertLike(_a0 *domain.Like) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Like) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
