// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "instagram-go/domain"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindOneUser provides a mock function with given fields: filter
func (_m *UserRepository) FindOneUser(filter interface{}) (*domain.User, error) {
	ret := _m.Called(filter)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(interface{}) *domain.User); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUser provides a mock function with given fields: _a0
func (_m *UserRepository) FindUser(_a0 interface{}) (*[]primitive.M, error) {
	ret := _m.Called(_a0)

	var r0 *[]primitive.M
	if rf, ok := ret.Get(0).(func(interface{}) *[]primitive.M); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]primitive.M)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUser provides a mock function with given fields: _a0
func (_m *UserRepository) InsertUser(_a0 *domain.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *UserRepository) UpdateUser(_a0 *domain.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
