// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// UserHandler is an autogenerated mock type for the UserHandler type
type UserHandler struct {
	mock.Mock
}

// AuthenticateUser provides a mock function with given fields: _a0, _a1
func (_m *UserHandler) AuthenticateUser(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// PostUser provides a mock function with given fields: _a0, _a1
func (_m *UserHandler) PostUser(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// PutUser provides a mock function with given fields: _a0, _a1
func (_m *UserHandler) PutUser(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
